[tool.ruff]
line-length = 120

[tool.djlint]
profile="django"
ignore = "H023,H025,H031,D018"

reformat = true

[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
